# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  #vmImage: ubuntu-latest
  name: my-ubuntu

variables:
  buildConfiguration: 'Release'
  versionNumber: '1.1.$(Build.BuildId)'
  #versionNumber: '1.0.0'
  #Major: '1'
  #Minor: '0'
  #Patch: '0'


steps:

- script: |
    rm -rf $(Build.ArtifactStagingDirectory)/*
  displayName: 'Clean build directory'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '**/*.csproj'
