trigger:
- main

pool:
  #vmImage: ubuntu-latest
  name: my-ubuntu

variables:
  major: '1'
  minor: '0'
  revision: $[counter(variables['minor'], 1)] # This will get reset every time minor gets bumped.
  nugetVersion: '$(major).$(minor).$(revision)'
  buildConfiguration: 'Release'

stages:
- stage: BuildAndPackage
  jobs:
  - job: BuildAndPackageJob
    displayName: 'Build and Package'
    steps:
    - script: |
        rm -rf $(Build.ArtifactStagingDirectory)/*
      displayName: 'Clean build directory'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: "dotnet pack"
      inputs:
        command: 'pack'
        configuration: $(BuildConfiguration)
        packagesToPack: '**/*.csproj'
        packDirectory: '$(Build.ArtifactStagingDirectory)'
        versionEnvVar: 'nugetVersion'
        versioningScheme: 'byEnvVar'
        nobuild: true

    - task: NuGetAuthenticate@1
      displayName: 'NuGet Authenticate'

    - task: NuGetCommand@2
      displayName: 'nuget push'
      inputs:
        command: 'push'
        feedsToUse: 'select'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'Dot Net Hello World/my-artifacts'
        vstsFeed: 'Dot Net Hello World/my-artifacts'
        versioningScheme: 'off'
        allowPackageConflicts: true

- stage: EchoVersion
  jobs:
  - job: EchoVersionJob
    displayName: 'Echo Version'
    steps:
    - script: |
        echo "NuGet Package Version: $(nugetVersion)"
      displayName: 'Echo NuGet Version'
